### ISSUE TITLE
CUDA Interop?

### ISSUE THREAD

**Issue by ib00** [chrismile/sgl#2]
Is there an example of how to use Vulkan and CUDA interop with sgl?

**Comment by chrismile** [comment]
At the moment, I'm using the Vulkan and CUDA interop support in this repository for interchanging data with the NVIDIA OptiX denoiser: https://github.com/chrismile/CloudRendering

In Main.cpp (https://github.com/chrismile/CloudRendering/blob/main/src/Main.cpp), the necessary Vulkan device extensions are queried with `sgl::vk::Device::getCudaInteropDeviceExtensions();`.

The rest of the relevant code can be found here: https://github.com/chrismile/CloudRendering/blob/main/src/Denoiser/OptixVptDenoiser.cpp

Instead of the CUDA driver API (which I'm using and where commands start with `cu`), you should also be able to use the CUDA runtime API (where commands start with `cuda`). These two APIs are compatible and objects from one API can be used where objects from the other API are expected.
